---

skip_if_no_internet: false
update_db: false
update_system: false

pacman:
    num_retries: 5
    disable_download_timeout: false
    needed_only: true

# The installer itself has no business remaining on a fresh install.
operations:
  - remove:
    - calamares
